vim.keymap.set("n", "<Esc>", vim.cmd.nohlsearch)
vim.keymap.set("i", "<C-c>", "<Esc>")
vim.keymap.set("n", "<LocalLeader>q", "<CMD>close<CR>")
vim.keymap.set({ "n", "v", "i" }, "<C-s>", "<CMD>w<CR>")

vim.keymap.set("n", "#", "#zzzv")
vim.keymap.set("n", "*", "*zzzv")
vim.keymap.set("n", "n", "nzzzv")
vim.keymap.set("n", "N", "Nzzzv")
vim.keymap.set("n", "<C-b>", "<C-b>zz")
vim.keymap.set("n", "<C-d>", "<C-d>zz")
vim.keymap.set("n", "<C-f>", "<C-f>zz")
vim.keymap.set("n", "<C-u>", "<C-u>zz")

vim.keymap.set({ "n", "x" }, "<Leader>D", [["_D]])
vim.keymap.set({ "n", "x" }, "<Leader>d", [["_d]])
vim.keymap.set({ "n", "x" }, "<Leader>X", [["_X]])
vim.keymap.set({ "n", "x" }, "<Leader>x", [["_x]])
vim.keymap.set({ "n", "x" }, "<Leader>Y", [["+Y]])
vim.keymap.set({ "n", "x" }, "<Leader>y", [["+y]])

vim.keymap.set("i", ",", ",<c-g>u")
vim.keymap.set("i", ".", ".<c-g>u")
vim.keymap.set("i", ";", ";<c-g>u")

vim.keymap.set("i", "<C-a>", "<c-o>I")
vim.keymap.set("i", "<C-e>", "<c-o>A")
vim.keymap.set("i", "<C-r><C-f>", "<C-r>=expand('%:t:r')<CR>")

vim.keymap.set("n", "<C-h>", "<C-w>h", { desc = "[Pane] Left" })
vim.keymap.set("n", "<C-j>", "<C-w>j", { desc = "[Pane] Down" })
vim.keymap.set("n", "<C-k>", "<C-w>k", { desc = "[Pane] Up" })
vim.keymap.set("n", "<C-l>", "<C-w>l", { desc = "[Pane] Right" })
vim.keymap.set("n", "<C-Left>", "<CMD>vertical resize -1<CR>", { desc = "[Pane][Resize] To Left" })
vim.keymap.set("n", "<C-Right>", "<CMD>vertical resize +1<CR>", { desc = "[Pane][Resize] To Right" })
vim.keymap.set("n", "<C-Up>", "<CMD>resize +1<CR>", { desc = "[Pane][Resize] To Top" })
vim.keymap.set("n", "<C-Down>", "<CMD>resize -1<CR>", { desc = "[Pane][Resize] To Bottom" })

vim.keymap.set("n", "<Leader>ld", vim.diagnostic.open_float, { desc = "Show diagnostic" })
vim.keymap.set("n", "<LocalLeader>md", require("simple.util.diagnostic").toggle, { desc = "Toggle diag" })
-- stylua: ignore
vim.keymap.set("n", "<LocalLeader>mi", function() vim.lsp.inlay_hint.enable(0, not vim.lsp.inlay_hint.is_enabled()) end, { desc = "Toggle inlay hint" })
